// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClLNZMHDAF6TfQtcVahVWyL2ck3--xkxk',
    appId: '1:690512973236:web:ea063b7ba7ae5b391676e1',
    messagingSenderId: '690512973236',
    projectId: 'break-down-assist-3f418',
    authDomain: 'break-down-assist-3f418.firebaseapp.com',
    storageBucket: 'break-down-assist-3f418.appspot.com',
    measurementId: 'G-BQ79RV5RNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGdwiDSVwzDWAm20WO2P9gs4VwmbtxI9M',
    appId: '1:690512973236:android:1130943eaa3eb71c1676e1',
    messagingSenderId: '690512973236',
    projectId: 'break-down-assist-3f418',
    storageBucket: 'break-down-assist-3f418.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Y_Jr20Ssmgo01LFiu3SlG3wqbkpL4DY',
    appId: '1:690512973236:ios:bf2587f3ffa24f801676e1',
    messagingSenderId: '690512973236',
    projectId: 'break-down-assist-3f418',
    storageBucket: 'break-down-assist-3f418.appspot.com',
    iosBundleId: 'com.example.breakdownAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Y_Jr20Ssmgo01LFiu3SlG3wqbkpL4DY',
    appId: '1:690512973236:ios:78922bf5b37d9d9d1676e1',
    messagingSenderId: '690512973236',
    projectId: 'break-down-assist-3f418',
    storageBucket: 'break-down-assist-3f418.appspot.com',
    iosBundleId: 'com.example.breakdownAssist.RunnerTests',
  );
}
